version: "3"
services:
  web:
    # image: <backend_image_repo>:latest
    build: ./docsbox
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
      - docsbox:/home/docsbox
      - media:/home/docsbox/media
    extra_hosts:
      - it1.integraatiopalvelu.fi:46.30.128.27
    command: gunicorn -b :8000 docsbox:app
 
  rqworker:
    # image: <backend_image_repo>:latest
    build: ./docsbox
    depends_on:
      - redis
      - web
    volumes:
      - docsbox:/home/docsbox
      - media:/home/docsbox/media
    command: rq worker -c docsbox
 
  rqscheduler:
    # image: <backend_image_repo>:latest
    build: ./docsbox
    depends_on:
      - redis
      - web
    command: rqscheduler -H redis -p 6379 -d 0
 
  nginx:
    # image: <proxy_image_repo>:latest
    build: ./nginx
    depends_on:
      - web
    ports:
      - "80:80"
 
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  docsbox:
  media:
  redis-data: